[package]
name = "proc-macro-example"
version = "0.1.0"
authors = ["Kaichao Sun <kaichaosuna@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
proc-macro-crate = "0.1.4"
